### ISSUE TITLE
Crashes with thread '<unnamed>' panicked at 'failed to invoke plugin

### ISSUE THREAD

**Issue by AbhiPrasad** [magic-akari/swc_mut_cjs_exports#30]
`@swc/jest` causes jest to crash in CI when using the [`jest_workaround` plugin](https://github.com/magic-akari/jest_workaround).

GH action run: https://github.com/getsentry/sentry-javascript/actions/runs/4437301786/jobs/7787193218

PR w/ crash: https://github.com/getsentry/sentry-javascript/pull/7484

SWC versions:
```
    "@swc/core": "1.3.40",
    "@swc/jest": "0.2.24",
```

`jest_workaround` versions:
```
  "jest_workaround": "0.1.16",
```

```
> @sentry/core:test

$ jest
thread '<unnamed>' panicked at 'failed to invoke plugin: failed to invoke plugin on 'Some("/home/runner/work/sentry-javascript/sentry-javascript/packages/core/test/lib/base.test.ts")'

Caused by:
    0: RuntimeError: out of bounds memory access
    1: heap_get_oob', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/swc-0.255.3/src/plugin.rs:228:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Segmentation fault (core dumped)
error Command failed with exit code 139.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

SWC bug report: https://github.com/swc-project/swc/issues/7092

https://github.com/swc-project/swc/issues/7092#issuecomment-1473540423

**Comment by magic-akari** [comment]
I cannot checkout the code, have you deleted the branch?

**Comment by AbhiPrasad** [comment]
Hey sorry @magic-akari, I pushed the branch up: https://github.com/getsentry/sentry-javascript/tree/abhi-build-swc-jest

**Comment by pneme** [comment]
This is not fixed. Happens to me also after upgrading to TS 5.0.

**Comment by AbhiPrasad** [comment]
@pneme what is your exact versions for:
- TS
- @swc/core
- @swc/jest
- jest_workaround

you need to make sure that your versions all align properly.

**Comment by pneme** [comment]
@AbhiPrasad 

"jest_workaround": "^0.72.6",
"@swc/core": "^1.3.44",
"@swc/jest": "^0.2.24"
"typescript": "^5.0.4"

**Comment by pneme** [comment]
@AbhiPrasad 

Just updated to:
"@swc/core": "^1.3.51",
"@swc/jest": "^0.2.26",

Now I'm getting `failed to invoke `jest_workaround` as js transform plugin at`

**Comment by pneme** [comment]
@AbhiPrasad Could you send me your setup that works, please?

**Comment by AbhiPrasad** [comment]
@pneme - I used https://github.com/getsentry/sentry-javascript/compare/develop...abhi-build-swc-jest

But had to end up dropping swc because of the esm module immutability problem (couldn't do any monkey patching :/)

**Comment by pneme** [comment]
@magic-akari This MR unfortunately does not have TS 5

**Comment by Lefschetz** [comment]
@AbhiPrasad I came across the same issue  recently. From the discussion above, I cannot catch the workaround. Any ideas to fix it?

**Comment by AbhiPrasad** [comment]
Hey @Lefschetz, it's been a while since I've looked at this. I recommend creating a new GH issue with a minimal reproduction so that the maintainers can take a look!

**Comment by jrolfs** [comment]
I found I had an out-of-date version of **@swc/core** installed, and upgrading to the latest resolved this.
